export type { ClockProps } from "./clock"
export { Clock } from "./clock"
export type { GaugeProps } from "./gauge"
export { Gauge } from "./gauge"
export type { FaceShape, MainplateProps } from "./mainplate"
export { Mainplate } from "./mainplate"
export type { CapProps, DialProps, HandProps, TicksProps } from "./parts"
export { Cap, Dial, Hand, Ticks } from "./parts"
